name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: Initiate
        run: npm ci
      - name: Build Potori
        run: npm run build
      - name: Build Documents
        run: npm run build:docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_DEPLOY }}
          publish_dir: ./dist
          cname: potori.lucka.moe