name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: 12.x
      - name: Initiate
        run: npm ci
      - name: Build Potori
        run: npm run build
      - name: Build Documents
        run: npm run build:docs