# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_DEPLOY }}
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Initiate
      run: |
        npm ci
        git config --global user.name "Lucka"
        git config --global user.email "samzhao0727@gmail.com"
    - name: Build Potori
      run: npm run build
    - name: Build Documents
      run: npm run build:docs
    - name: Deploy
      run: npm run deploy
